name: Exercism sync auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  merger:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'exercism-solutions-syncer[bot]' }}
    steps:
      - name: Enable auto-merge for Exercism syncer PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
